spring:
  h2:
    console:
      enable: true
  datasource:
    generate-unique-name: false
    name: 'social-account'
    url: 'jdbc:h2:file:./social-account-db'
  jpa:
    hibernate:
      ddl-auto: 'update'
      dialect: 'org.hibernate.dialect.H2Dialect'
logging:
  level:
    org:
      hibernate:
        SQL: 'DEBUG'
        type:
          descriptor:
            sql:
              BasicBinder: 'TRACE'
      springframework:
        jdbc: 'DEBUG'

---
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enable: true
  datasource:
    generate-unique-name: false
    name: 'social-account-test'
    url: 'jdbc:h2:file:./social-account-db-test'
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
      dialect: 'org.hibernate.dialect.H2Dialect'
logging:
  level:
    org:
      hibernate:
        SQL: 'DEBUG'
        type:
          descriptor:
            sql:
              BasicBinder: 'TRACE'
      springframework:
        jdbc: 'DEBUG'