spring:
  h2:
    console:
      enable: true
  datasource:
    generate-unique-name: false
    name: 'social-account'
    url: 'jdbc:h2:file:./social-account-db'
  jpa:
    hibernate:
      ddl-auto: 'update'
logging:
  level:
    org:
      hibernate:
        SQL: 'DEBUG'
        type:
          descriptor:
            sql:
              BasicBinder: 'TRACE'
      springframework:
        jdbc: 'DEBUG'